# Generated by Django 5.0.4 on 2024-04-27 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_field', models.CharField(max_length=100, verbose_name='Job Field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, verbose_name='Question')),
                ('answer', models.TextField(blank=True, verbose_name='Answer')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='resume.resume')),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='technology_stack',
            field=models.ManyToManyField(to='resume.technology', verbose_name='Technology Stack'),
        ),
    ]
