# Generated by Django 5.0.4 on 2024-04-27 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobfield', verbose_name='Job Field'),
        ),
    ]
