# Generated by Django 5.0.4 on 2024-04-29 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_jobfield_alter_resume_job_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume')),
            ],
        ),
    ]
